version: '3.7'

services:
  server:
    container_name: financialnotification-api
    entrypoint: [ "sh", "-c", "java -cp app:app/lib/* br.com.geradordedevs.financialnotification.FinancialNotificationApplication" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://financial-notification-db:3306/db_financial?createDatabaseIfNotExist=true
      - DATABASE_HOST=db-financial
      - DATABASE_USER=db_financial
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=db_financial
      - DATABASE_PORT=3306

    depends_on:
      - db-financial

  db-financial:
    image: mysql:8.0
    container_name: financial-notification-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_financial
      - MYSQL_USER=db_financial
      - MYSQL_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - ./data/db:/data/db